name: message_copperframe
description: "A new Flutter package project."
version: 0.0.1
homepage:

environment:
  sdk: ^3.4.4
  flutter: "3.24.0"

dependencies:
  flutter:
    sdk: flutter
  grand_copperframe:
    git:
      url: https://github.com/flarebyte/grand_copperframe.git
      ref: v0.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

